#!/usr/bin/env python3
"""End-to-end suite: boot the real alego (from this repo's node_modules) with
the alego-base bundle + the built tui plugin + a scripted mock LLM, inside a
real PTY, and drive full user scenarios.

Phase 1 (fixed session id): streaming, tools, approvals, questions, plan review,
todos, child agents, interruption, model routing, title rename, and clean exit.
Phase 2 (fresh boot): list the saved title, resume its transcript, and exit.

Everything (CLI, loader, harness packages, plugin externals) resolves from
this repo's node_modules, so there is exactly one copy of every
@singula-ai package in the process.
"""
import fcntl
import json
import os
import pty
import re
import select
import shutil
import signal
import struct
import subprocess
import sys
import termios
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HOME = ROOT / ".alego-dev-home"
PROFILE = HOME / "profiles" / "cc"
PATCH = HOME / "dev.cordis.yml"

PROMPT_GLYPH = "❯"
FIXED_SID = "cc-e2e-fixed-session"


def bootstrap(fixed_session: str | None) -> None:
    PROFILE.mkdir(parents=True, exist_ok=True)
    modules = PROFILE / "node_modules"
    modules.mkdir(exist_ok=True)
    plugin = modules / "alego-tui"
    if not plugin.exists():
        plugin.symlink_to(ROOT, target_is_directory=True)
    (PROFILE / "package.json").write_text(
        json.dumps(
            {
                "name": "alego-profile-cc",
                "private": True,
                "dependencies": {},
                "alego": {"profile": {"bundles": ["@singula-ai/alego-base", "alego-tui"]}},
            },
            indent=2,
        )
    )
    session_line = f"\n    sessionId: '{fixed_session}'" if fixed_session else ""
    PATCH.write_text(
        f"""
# generated by scripts/e2e/run_core.py
- id: tui
  config:
    provider: mock
    model: mock-1
    cwd: '{ROOT}'{session_line}
- insert:
    - id: mock-llm
      name: '{ROOT}/test/e2e/mock-llm.mjs'
"""
    )


class TuiSession:
    """One alego boot inside a PTY, with a minimal query-answering terminal."""

    def __init__(self, label: str) -> None:
        self.label = label
        self.transcript = bytearray()
        self.checkpoint = 0
        self.clean_exit = False
        self.answered: set[str] = set()
        env = dict(os.environ)
        env["ALEGO_HOME"] = str(HOME)
        env["NODE_ENV"] = "production"
        env["ALEGO_TUI_INLINE"] = "1"
        env["ALEGO_TUI_HOME"] = str(HOME / "tui")
        env["TERM"] = "xterm-256color"
        env["ALEGO_TUI_TRUECOLOR"] = "1"
        env["FORCE_COLOR"] = "3"
        env.pop("NO_COLOR", None)
        env.pop("ALEGO_TUI_THEME", None)
        cmd = [
            "node",
            str(ROOT / "node_modules" / "@singula-ai" / "alego" / "lib" / "bin.js"),
            "--profile",
            "cc",
            "--patch",
            str(PATCH),
        ]
        self.master, slave = pty.openpty()
        fcntl.ioctl(slave, termios.TIOCSWINSZ, struct.pack("HHHH", 40, 120, 0, 0))
        os.set_inheritable(slave, True)
        self.proc = subprocess.Popen(
            cmd,
            stdin=slave,
            stdout=slave,
            stderr=slave,
            env=env,
            cwd=str(ROOT),
            close_fds=True,
            preexec_fn=os.setsid,
        )
        os.close(slave)

    def _answer_queries(self, chunk: bytes) -> None:
        replies = []
        if b"\x1b[c" in chunk or b"\x1b[0c" in chunk:
            replies.append(b"\x1b[?62;22c")
        for _ in re.findall(rb"\x1b\[6n", chunk):
            replies.append(b"\x1b[40;1R")
        if (b"\x1b]11;?" in chunk) and ("osc11" not in self.answered):
            self.answered.add("osc11")
            replies.append(b"\x1b]11;rgb:1e1e/1e1e/1e1e\x1b\\")
        if b"\x1b[?2026$p" in chunk:
            replies.append(b"\x1b[?2026;2$y")
        if replies:
            os.write(self.master, b"".join(replies))

    def flat(self, since: int = 0) -> str:
        t = bytes(self.transcript[since:]).decode("utf-8", "replace")
        t = re.sub(r"\x1b\[[0-9]*C", " ", t)
        t = re.sub(r"\x1b\[[0-9;?<>=]*[A-Za-z]", "", t)
        t = re.sub(r"\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)", "", t)
        t = re.sub(r"[\r\n]+", " ", t)
        return re.sub(r"\s+", " ", t)

    def read_until(self, needles: list[str], timeout: float) -> str | None:
        deadline = time.time() + timeout
        while time.time() < deadline:
            r, _, _ = select.select([self.master], [], [], 0.25)
            if self.master in r:
                try:
                    chunk = os.read(self.master, 65536)
                except OSError:
                    break
                if not chunk:
                    break
                self.transcript.extend(chunk)
                self._answer_queries(chunk)
            flat = self.flat(self.checkpoint)
            for needle in needles:
                if needle in flat:
                    return needle
            if self.proc.poll() is not None:
                try:
                    while True:
                        chunk = os.read(self.master, 65536)
                        if not chunk:
                            break
                        self.transcript.extend(chunk)
                except OSError:
                    pass
                break
        flat = self.flat(self.checkpoint)
        for needle in needles:
            if needle in flat:
                return needle
        return None

    def drain(self, seconds: float) -> None:
        end = time.time() + seconds
        while time.time() < end:
            r, _, _ = select.select([self.master], [], [], 0.2)
            if self.master in r:
                try:
                    chunk = os.read(self.master, 65536)
                except OSError:
                    return
                if not chunk:
                    return
                self.transcript.extend(chunk)
                self._answer_queries(chunk)
            if self.proc.poll() is not None:
                return

    def send(self, data: bytes) -> None:
        os.write(self.master, data)

    def type_line(self, text: bytes) -> None:
        self.checkpoint = len(self.transcript)
        self.send(text)
        self.drain(0.5)
        if text.startswith(b"/"):
            # a bare slash word opens the completion menu, whose Enter ACCEPTS
            # instead of submitting; Esc dismisses it first
            self.send(b"\x1b")
            self.drain(0.3)
        self.send(b"\r")

    def finish(self, quit_first: bool = True) -> None:
        try:
            if quit_first and self.proc.poll() is None:
                self.type_line(b"/quit")
                self.drain(2.0)
            self.proc.wait(timeout=20)
            self.clean_exit = self.proc.returncode == 0
        except subprocess.TimeoutExpired:
            pass
        finally:
            if self.proc.poll() is None:
                try:
                    os.killpg(self.proc.pid, signal.SIGKILL)
                except OSError:
                    pass
            try:
                os.close(self.master)
            except OSError:
                pass
            (HOME / f"e2e-{self.label}.transcript").write_bytes(bytes(self.transcript))


def banner_is_amber(raw: str) -> bool:
    """Every SGR truecolor run painting the wordmark/brick must be amber-dominant.

    Asserts COLOR, not glyphs: upstream once shipped a rebrand that changed the
    ASCII art and kept the previous brand's palette, and a glyph-only check
    passed it.
    """
    i = raw.find("\u2588\u2588")  # first wordmark block glyph
    if i < 0:
        return False
    window = raw[max(0, i - 400):i + 2500]
    codes = [tuple(map(int, m)) for m in re.findall(r"\x1b\[38;2;(\d+);(\d+);(\d+)m", window)]
    brand = [c for c in codes if max(c) - min(c) > 30]  # ignore greys/chrome
    if not brand:
        return False
    return all(r > b and g > b for r, g, b in brand[:8])


def phase1(failures: list[str]) -> None:
    # the write-tool scenario must CREATE the probe file, not update a leftover
    (ROOT / "e2e-scratch" / "e2e-write-probe.txt").unlink(missing_ok=True)
    bootstrap(FIXED_SID)
    s = TuiSession("phase1")
    try:
        if not s.read_until([PROMPT_GLYPH], 60):
            failures.append("p1: composer prompt never rendered")
            return
        s.drain(1.0)
        s.type_line(b"hello harness")
        if not s.read_until(["MOCK-REPLY: hello harness", "harness agent failed"], 45):
            failures.append("p1: full mock reply never rendered")
        elif "harness agent failed" in s.flat():
            failures.append("p1: agent failed to start")
        s.drain(1.0)
        # approval round-trip via sandbox escalation
        s.type_line(b"please USE-BASH now")
        gate = s.read_until(["Yes", "harness agent failed"], 45)
        if gate is None:
            failures.append("p1: approval prompt never appeared")
        elif gate == "Yes":
            s.drain(0.5)
            s.send(b"1")
            if not s.read_until(["TOOL-STEP-DONE"], 45):
                failures.append("p1: bash turn never completed after approval")
        s.drain(1.5)
        # diff card: fs write tool creates a file, the transcript shows the card
        s.type_line(b"please USE-WRITE now")
        if not s.read_until(["Wrote", "alpha", "TOOL-STEP-DONE"], 45):
            failures.append("p1: write tool turn never rendered")
        s.read_until(["TOOL-STEP-DONE"], 30)
        s.drain(1.0)
        # harness command bridge
        s.type_line(b"/e2eprobe")
        if not s.read_until(["EPROBE-BRIDGE-OK"], 20):
            failures.append("p1: harness command bridge failed")
        # Questions use the real ask_user_question tool and answerer waterfall.
        s.type_line(b"please USE-QUESTION now")
        if s.read_until(["1. Amber", "Error: unknown tool"], 20) == "1. Amber":
            s.drain(0.5)
            s.send(b"1")
            if not s.read_until(['QUESTION-RESULT:', 'harness agent failed'], 20):
                failures.append("p1: question tool did not resume")
        else:
            failures.append("p1: question prompt never appeared")
        s.drain(1.0)
        s.type_line(b"/e2eplan")
        if s.read_until(["E2E PLAN CONTENT"], 20):
            s.drain(0.5)
            s.send(b"\r")
            if not s.read_until(["PLAN-RESULT: Approve plan"], 20):
                failures.append("p1: plan review did not resume")
        else:
            failures.append("p1: plan review never appeared")
        s.drain(1.0)
        s.type_line(b"please USE-TOOL now")
        if not s.read_until(["TOOL-STEP-DONE"], 20):
            failures.append("p1: todo tool never completed")
        s.drain(1.0)
        s.type_line(b"please USE-CHILD now")
        if not s.read_until(["CHILD-RESULT:"], 40):
            failures.append("p1: child agent never completed")
        s.drain(1.0)
        # Observe a live delta, interrupt before settlement, then send a new turn.
        s.type_line(b"please USE-SLOW now")
        if not s.read_until(["STREAM-IN-PROGRESS"], 8):
            failures.append("p1: live stream delta never rendered")
        if "STREAM-FINISHED" in s.flat(s.checkpoint):
            failures.append("p1: stream was buffered until completion")
        s.send(b"\x1b")
        s.drain(2.0)
        s.type_line(b"after interruption")
        if not s.read_until(["RECOVERY-OK"], 20):
            failures.append("p1: composer did not recover after interruption")
        s.drain(1.0)
        # live model switch reflects in the stats line
        s.type_line(b"/model mock-2")
        if not s.read_until(["mock-2"], 20):
            failures.append("p1: model switch never reflected")
        s.drain(1.0)
        s.type_line(b"please USE-MODEL now")
        if not s.read_until(["MODEL-REPLY: mock-2"], 20):
            failures.append("p1: switched model did not reach the provider")
        s.drain(1.0)
        s.type_line(b"/title E2E Saved Session")
        if not s.read_until(["session title set: E2E Saved Session"], 20):
            failures.append("p1: title rename failed")
        s.drain(1.0)
    finally:
        s.finish()
    flat = s.flat()
    raw_text = bytes(s.transcript).decode("utf-8", "replace")
    for label, ok in [
        ("p1 banner/composer rendered", PROMPT_GLYPH in flat),
        # Verify the shipped amber palette as well as the wordmark.
        ("p1 banner painted in Alego amber", banner_is_amber(raw_text)),
        ("p1 mock reply streamed", "MOCK-REPLY: hello harness" in flat),
        ("p1 approval prompt shown", "Yes" in flat and "bash" in flat),
        ("p1 approved tool ran to completion", "TOOL-STEP-DONE" in flat),
        ("p1 harness command bridged", "EPROBE-BRIDGE-OK" in flat),
        ("p1 write diff card rendered", "e2e-write-probe.txt" in flat and "alpha line" in flat and ("Wrote" in flat or "+alpha" in flat)),
        ("p1 model switch reached provider", "MODEL-REPLY: mock-2" in flat),
        ("p1 question answer returned by id", '"color"' in flat and '"Amber"' in flat and "QUESTION-RESULT:" in flat),
        ("p1 plan review answered", "PLAN-RESULT: Approve plan" in flat),
        ("p1 todo snapshot rendered", "mock todo item" in flat),
        ("p1 child agent result returned", "CHILD-RESULT:" in flat and "MOCK-REPLY: hello child" in flat),
        ("p1 interrupted stream recovered", "RECOVERY-OK" in flat and "STREAM-FINISHED" not in flat),
        ("p1 file write reached disk", (ROOT / "e2e-scratch/e2e-write-probe.txt").read_text() == "alpha line\nbeta line\n"),
        ("p1 clean exit", s.clean_exit),
        ("p1 no unhandled errors", "Unhandled" not in flat and "harness agent failed" not in flat),
    ]:
        print(f"  {'PASS' if ok else 'FAIL'}  {label}")
        if not ok:
            failures.append(label)


def phase2(failures: list[str]) -> None:
    bootstrap(None)  # fresh session this time
    s = TuiSession("phase2")
    try:
        if not s.read_until([PROMPT_GLYPH], 60):
            failures.append("p2: composer prompt never rendered")
            return
        s.drain(1.0)
        s.type_line(b"/sessions")
        if not s.read_until(["E2E Saved Session"], 20):
            failures.append("p2: persisted session missing from picker")
        s.send(b"\x1b")
        s.drain(0.5)
        s.type_line(b"/sessions " + FIXED_SID.encode())
        if not s.read_until(["MOCK-REPLY: hello harness"], 45):
            failures.append("p2: resumed transcript never replayed")
        s.drain(1.0)
    finally:
        s.finish()
    flat = s.flat()
    for label, ok in [
        ("p2 resume replayed prior turn", "MOCK-REPLY: hello harness" in flat),
        ("p2 persisted title listed", "E2E Saved Session" in flat),
        ("p2 clean exit", s.clean_exit),
        ("p2 no unhandled errors", "Unhandled" not in flat and "harness agent failed" not in flat),
    ]:
        print(f"  {'PASS' if ok else 'FAIL'}  {label}")
        if not ok:
            failures.append(label)


def run() -> int:
    # deterministic session store per run
    shutil.rmtree(HOME, ignore_errors=True)
    failures: list[str] = []
    phase1(failures)
    phase2(failures)
    if failures:
        print(f"\ne2e FAILED: {failures}")
        for name in ("phase1", "phase2"):
            p = HOME / f"e2e-{name}.transcript"
            if p.exists():
                text = p.read_bytes().decode("utf-8", "replace")
                print(f"--- {name} tail ---")
                print(text[-1500:])
        return 1
    print("\ne2e PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(run())
